{%set name = "netifaces" %}
{%set version = "0.10.5" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "59d8ad52dd3116fcb6635e175751b250dc783fb011adba539558bd764e5d628b" %}
{%set build_num = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - netifaces

about:
  home: https://bitbucket.org/al45tair/netifaces
  license: MIT
  license_family: MIT
  summary: 'Portable network interface information.'
  dev_url: https://bitbucket.org/al45tair/netifaces

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
