# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "njNOO9kI+a7J7XAhR8EME3uIAHiGGQd7vX8g7IaGkdYnC1uLUN7rOvGmwMaM3tGSwxjIQhn17sc07Nnv7q8+MWHAgSiMlnGT9tiAZxx1JbzWJFWVkDhZpHuzcOcluSvu5yafHTEI3+Ry3swUJmMwNnp9z7BeYUaiQeSTWhiQTYK0CRn/oc+lX0ALT0oqqLYsOKAOp1zgyFemtux/fmmG62dMRlL+cZKK/1t1rTNyuE2HBkrpTBOgrm/rkBJdPmVbgaZaNVii6VTNT5tYMkLWGI3Ieqq+ye1DfPA2dqOHSXuQRx3WT44Wg+jNH4essXS1U5K+bDRP8mB6r+DordlV6dspfVvOwe0crDaT9waiqh76fzy8eirigI5dmd299NcxUxG1LK9GyKhW9j1lpJhvRb010RqmieM+Y4cEKEDbLmSGKQK8wY4B6u4HUJFG8UQsl4APS4M3WAEvPr3wm6VJFIhEmNB1x0ojYgJoTv2A9m7Y6Z5why9HC7OzL2ts4vvfYJKX/3v16vYiA+kUD65EpbJ2zHi9l94a/0iIahrhqvGQJHoHG488I/5xRY6RINqVkaQUBy9oaDjMEmfMu15LZHYWVk/A0FlqUUkapkkwdL40ImLF5FAY4Kw4BYYCwKK/EupjrIn2qRDFD4boB4+PIO0Mv+D4V2cKNJs4bzKeAJ8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
