travis:
  secure:
    BINSTAR_TOKEN: K4y4faFDPXQhKC9If62Jii18C2YuV61rlGPsy4G2BQbkzv9f1dvxDTsbregYRRQxcOxlCQio69dMAsfqRe2N4px3kg6hPcc/f1/OTzDlZ6VE8rB+mL/WJs+rxGK1hrYes2SXMo17n3H9zBwKCSrLo2hGPpitSZGzghrYv1LqS8hTYtzlnDJ0UE1D/4Xg/ShfuOV24UKCzwNrd9v1izM81FTt0LYeT55xzBaOD1KyGyyCAGuLuN59U9jlVmj/3a8iJjRla12XbMdq+6mAFm0/ruLPhMF9cJL4Mi947ip+sYh7Y49se5mZo0dMDe0De7na/lXI7YMCnYKGiSWJAfNgJY31tykgcf/RXqbhTNy5/E0YL7cyjfyqx0x3L9owjHmAb7RoWrErpUf93k1YdzuHouLQYA5ujGaRynPWWmcMRWqrRCdn+MLTGpgZZN/rz1Yb+7nQDgc877U6otECU0QrvWm43HXWadS5vMlyw67aphoiJbEumqC6BByTpFJrR/pIZPYDkb7SxfNz43wgAi5+M4nVwIe4aZB8z7rWUxvCetgZx5eI9fT72/d658XDxolL4BIVod1eOhfw/LvO1OG+unJ1sYga/G32sxSm/ZxJk/NPotd9+yWhJJazBvHxw3RtWLS5TxfmqpVQIkSIjfRu4QzLALqXdpREfetkPN5bqMU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
