travis:
  secure:
    BINSTAR_TOKEN: RJPU0gvozp0E0rKDu3AEDJ9YfdhX8ODj0vgXzLh82IFELXmf/tFCBW34/GHGj9twT6KjDkueWSGqXYjS299JvcwxzIB1UAJLyKkXKcLcacqlWb1otJHuXLmB6j4ni3LTZPx6I2TiDMtJok78MvDeOOXnqUgXdqDjoUZMNJ4+CgVeF3FGSiuw1mUrJlhE28PFW5dv6Y29Ncj+j4xS71QlNHwNde/V4TUWE2M2GBjNrbsiZ4KI6gfDLThyBrInO4xni0TvW8wKNliaQX++HjMin97uqTPo6JEG7ROGfsI6ENKBRvoGv1chs5u1RlskUcd3L5ssqEJ/BLFjudoTGQscRRHpPCmtP78VXqa09PtDVAt/BffIvFKZq7TIOXgm/8R9+nU9Ur4o7tb5e78ub/eDDa8HxWhMWbxylcEFQ3i91BZeL3rrhzq7JzYsMxAw4QUma5Ye7tcdNtNqNeUWztuqw1+SoAtCO589ocVpj/9z855yLnBlQhlp1lCXJqVDDCORpkU0r2s8/bhjzZal8fwt6Te126m/AuSE9tooad9vV5Ud30jx05SqnRyH1E8Nse+pxVmhdEZa3eNozxv6r3+oc/vHAxAJGZBTZEzX/U3wsEpaezhHUhU3M6GaRIQG3todP52JvZ/guIPihupS4cDVyMEqq0PA7jNXgSftTF0ZeXg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
