travis:
  secure:
    BINSTAR_TOKEN: UvIqspNDP9c40+p+1FCZoYBwanaRk61l+BNIKYcXZt/6OrkSPYnOeaOG7SWLFOJg5hRoeFPifxyi9rqk9J+hCSA0u4o8IQdjGGF9epephe3CcKQD7WIfP9LvT074UGUXztcKZhd/+CgtvwvIWrsaPSy4fDPsYDPLlYNTwXJOAyc+JUtRUhtIwVWb3Y39Dy/aciUEVhaORskX5SoOp1TyEdJRugcnNCKFxp22x8vTs8K9m43Mgz4+OjX88p+rpEzaVnJVw9zkCE7h1Frwt+qkKzn3TkEo1rkkaRHt3q3VTxJl6O25Kjuhz7jHWMqjGM2g1XcUfr1aajRV0IcQLmIPyR6OD6dwd9kJoX5CbdgaiTBLkEZbivTish/uPqi9zfASUkW0omS2JWBHC9ISHkClRKsqbGQLZgp9jZm6xCa5wXewylCf0/SU1W474HkuyR/FrJmoFyH4DJgbvC6f9eCDAaqiYl37GUl9RLU6FkDIMJmCWgQ+TB2KK37As9H8cz/9fVXg/FoJG9l9fqf3oQo9QIYgZkuYVO9aBK6ZdmSeXDn4Gumug8dz4h9xCwKde9F1ikmFVSUxNhNo6E+refNvdLgk7nlQT0Jg21ZNfeEN2WUNReo9NRNY5a4u7id9uX36X7azA35qNf/w35hdBg/gFXQ9VfZqVcGyfTTUxTpAE0s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
