travis:
  secure:
    BINSTAR_TOKEN: iRbE8Uiv858EANOMH10xYXU84xNUsCGchVWCiDF6mF7dHkYdA2tUKa5mzXZ7i2+6wea/xyUoeLvbnlU5MMvzivZA9TilKNuOEGEC/zIr2jYSU6OrgRLgqwCcdH5uQlPADK0to2v//WqXyqGJj8wsURSjMWtOlAoQE+L4d17yqsHcWbqx7MRdqU98FOo5AWiEfLpF9h/qMSoeVHTkofcQRfvsAh/tcXX204mZ4Uv3zmdmY+x1JdEUEAQNqZwnP6NfsefNd9EJ+L+FnnOdJBlIllQQMcGAnyyhCN8En0yUXAmrOM0PNX6pqQ+kxZVWtpgq+ZWBx0iJkafwgZGlGNoOGje6Ktp6zhiJRhjqF7yyfUnzxQdqc7pITGMcMnWIYEDiwYNb5uU2uivOJOcMzD7DwhsCOW5IqJCXF72PJmuiA16GvjooRjO8b3U7k4wKxLds1Pwurl1uKAQ4iYpUrtEKlw/CQCvWa5SKCWMVRsVopnzIF9ygTH2yTz57XXeJr0wy9u6hXvXsIN5BX9+bmctPQ/yEBVvWt2NJWqo8I0jSs07mXXB0DBRt1+E3jEdTJtOP/9nRron1oBh4kt8+03zCmMr2/Y6hrfyk8TB+aa1P7ndPjisaBmB5TQ0TA+yyl8SsdHUkDopoyXd/7E0Ff3ZUGpplHoc0nieZkjTiF+otXNY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
