travis:
  secure:
    BINSTAR_TOKEN: njNOO9kI+a7J7XAhR8EME3uIAHiGGQd7vX8g7IaGkdYnC1uLUN7rOvGmwMaM3tGSwxjIQhn17sc07Nnv7q8+MWHAgSiMlnGT9tiAZxx1JbzWJFWVkDhZpHuzcOcluSvu5yafHTEI3+Ry3swUJmMwNnp9z7BeYUaiQeSTWhiQTYK0CRn/oc+lX0ALT0oqqLYsOKAOp1zgyFemtux/fmmG62dMRlL+cZKK/1t1rTNyuE2HBkrpTBOgrm/rkBJdPmVbgaZaNVii6VTNT5tYMkLWGI3Ieqq+ye1DfPA2dqOHSXuQRx3WT44Wg+jNH4essXS1U5K+bDRP8mB6r+DordlV6dspfVvOwe0crDaT9waiqh76fzy8eirigI5dmd299NcxUxG1LK9GyKhW9j1lpJhvRb010RqmieM+Y4cEKEDbLmSGKQK8wY4B6u4HUJFG8UQsl4APS4M3WAEvPr3wm6VJFIhEmNB1x0ojYgJoTv2A9m7Y6Z5why9HC7OzL2ts4vvfYJKX/3v16vYiA+kUD65EpbJ2zHi9l94a/0iIahrhqvGQJHoHG488I/5xRY6RINqVkaQUBy9oaDjMEmfMu15LZHYWVk/A0FlqUUkapkkwdL40ImLF5FAY4Kw4BYYCwKK/EupjrIn2qRDFD4boB4+PIO0Mv+D4V2cKNJs4bzKeAJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
