travis:
  secure:
    BINSTAR_TOKEN: OA6jV++Ud+puDq9qYGbY1iA0YHLazAQSbPytYh46qwlNfPQmle8U4ksofbRogA7NkYwOIwOntcRBgCPL/NkKbwWJFPbs57q0RjzmuLWbXhymf8w0ghaj0vEF8NZNCYww0G2jCHqh6UWmmPE6AKnjfYiAmk0lGaByJPqnCfmUiQ3rf6hif7QPN1faAX0K83HJrDVar3OCnU/z/Y1TOKmkRj9dA9ha0xvNqBYcvuENalB1qSbyiGfUnTdOzVmyYWyEW5jwVC8L36mkR3/vu2davlgbnZh61MH61KGPDcvzB3sjtsDIWmh7cPBY9EtWO7Yz09PSMwxBUvg2VqgGIBguPNg3quchuoIUzl7zC/VH9qEHkD/uvZot5kXRXtXyENLOq8pbGHryWeoMREhRExsyiDM3gXhkq2dX3uhghogPZn215Mhl+SbNR7361yNpgvFh3MXhOnjp9x3RhWccmI5yWWpYIlrMdG6BJ0GL4TilTgiyhH80QHAUpRc7BeNAgGGMq5sm//Nw/Dyn5UkXhu4A/8r9ho5ruIl03zCMg+cVr5muT6XxfrNpvIHsUCv+30B/t3tVLUSh6UiDdoE2ye7r9DQfD/ONKJt5z68ouAz2tvjqM6y/g6SyBTW71q8vbeE7bFy1yx+jGirOb1EV2dviCjnlxYaqFeB4tAFUPNTXpdE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
